language: ruby

pre:
 - gem update bundler

cache: bundler

rvm:
 - ruby
 - ruby-head
 - jruby
 - jruby-head

sudo: false

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
